project: lastqt
program: train.py
method: bayes
metric:
  goal: maximize
  name: best_auc
parameters:
  # valid_num: 
  #     values: [1, 2, 3, 4, 5] 
  hidden_dim:
    values: [32, 64, 128, 256, 512,1024]
  n_layers: 
    values: [1, 2, 4, 6,8,10] 
  n_heads:
    values: [1,2,4,8,16,32,64]
  lr: 
    values: [0.01, 0.05, 0.001, 0.005]
  max_seq_len:
    values: [50,200,500,800,1000,1200,1860]
  batch_size:
    values: [1,2,4,8,16,32,64,128,256,512]