project: lightGCN
program: train.py
method: bayes
metric:
  goal: maximize
  name: best_auc
parameters:
  valid_num: 
      values : [1, 2, 3, 4, 5] 
  embedding_dim:
      values : [16, 32, 64, 128, 256, 512]
  num_layers: 
      values : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
  learning_rate: 
    values : [0.01, 0.05, 0.001, 0.005, 0.0001]